// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daszoxmmxzaujnaswrwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhc3pveG1teHphdWpuYXN3cnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDkwMDUsImV4cCI6MjA2MjM4NTAwNX0.TIQb1SLerrTm3UmnBSGDgJrqcxLmcmt0NUAJYnxD0nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);